# -*- coding: utf-8 -*-
"""EXAMEN_algoritmos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19F70h51BWNqqT2ZCDb9fhWO3cRJ-jS8o
"""

precio_a = 3800
num_columna = 4
n_fila = 10

deptos_d = [
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
   [None, None, None, None],
]

def mostrar_deptos_d():
    print("Lotes disponibles:")
    for fila in deptos_d:
        for lote in fila:
            print('[X]' if lote == 'X' else '[ ]', end=' ')
        print()

def mostrar_ventas():
    if len(depto_seleccionado) == 0:
        print("No ha seleccionado ningun depto.")
        return

    for i, depto in enumerate(depto_seleccionado, start=1):
        fila, columna = depto
        n_depto = i
        cant_d = 1
        precio_total = cant_d * precio_a

        print(f"Detalles del departamento:", n_depto)
        print(f"Número de departamento: ", n_depto)
        print(f"Cantidad: ", cant_d)
        print(f"Ventas totales: $", precio_total)

depto_seleccionado = []

comprador = []

def mostrar_compradores():
    if len(comprador) == 0:
        print("Aún no hay compradores registrados en el sistema.")
        return

    print("Lista de Compradores:")
    print("------------------------------------")
    for cliente in comprador:
        rut = comprador
        print(f"RUT: ", rut)

    print("-------------------------------------")

def comprar_depto():
    while True:
        try:
            piso_d = int(input("Ingrese el piso que desea (1 al 10): "))
            print("")
            tipo_d = int(input("Ingrese el tipo de departamento que desea (1 al 4): "))
            print("")
        except ValueError:
            print("Opcion invalida. Intente nuevamente.")
            continue
        if piso_d < 0 or piso_d >= n_fila or tipo_d < 0 or tipo_d >= num_columna:
            print("Coordenadas invalidas. Intente nuevamente.")
            continue
        if deptos_d[piso_d][tipo_d] is None:
            break
        else:
            print("El lote seleccionado no se encuentra disponible. Seleccione otro.")

    print("")
    print("Ahora ingrese el RUT del comprador:")
    print("")
    rut_comprador = int(input("Ingrese rut de cliente (sin puntos ni guión): "))
    if rut_comprador < 10:
      print("rut invalido, reintente.")

    depto_seleccionado.append((piso_d, tipo_d))
    deptos_d[piso_d][tipo_d] = 'X'
    comprador.append((rut_comprador))
    print("")
    print("¡¡¡Felicidades!!!. Departamento comprado.")
    print("")

def salir_sistema():
  print("Saliendo del sistema. hasta luego!!!.")

while True:
  print("")
  print("¡¡¡Bienvenido a Casa Feliz!!!")
  print("1 - Comprar departamento.")
  print("2 - Departamentos disponibles.")
  print("3 - Ver lista de compradores.")
  print("4 - Mostrar ganancias totales.")
  print("5 - SALIR")
  print("")
  try:
    menu1 = int(input("Ingrese la opcion de su preferencia:"))

    if menu1 == 1:
      print("")
      comprar_depto()

    elif menu1 == 2:
      print("")
      mostrar_deptos_d()

    elif menu1 == 3:
      print("")
      mostrar_compradores()

    elif menu1 == 4:
      print("")
      print("Ganancias percibidas por ventas:")
      mostrar_ventas()

    elif menu1 == 5:
      print("")
      salir_sistema()
      break

  except ValueError:
    print("Valor ingresado invalido. Intente nuevamente.")